
server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: utf-8
      enabled: true
      force: true



spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: test00
    password: test00



  jackson:
    serialization:
      fail-on-empty-beans: false
mybatis:
  mapper-locations: classpath:/mapper/*.xml

